\c toonamania

INSERT INTO characters (name, age, image, description) VALUES
('Elena Rodriguez', 28, 'https://randomuser.me/api/portraits/women/1.jpg', 'Elena is a skilled engineer with a passion for robotics.'),
('Michael Thompson', 35, 'https://randomuser.me/api/portraits/men/2.jpg', 'Michael is a detective with a keen eye for detail and a mysterious past.'),
('Sophia Chang', 24, 'https://randomuser.me/api/portraits/women/3.jpg', 'Sophia is an aspiring artist who finds inspiration in nature.'),
('William Johnson', 42, 'https://randomuser.me/api/portraits/men/4.jpg', 'William is a chef known for his experimental cuisine and bold flavors.'),
('Olivia Smith', 30, 'https://randomuser.me/api/portraits/women/5.jpg', 'Olivia is a journalist who travels the world in search of stories.'),
('Benjamin Lee', 31, 'https://randomuser.me/api/portraits/men/6.jpg', 'Benjamin is a software developer fascinated by artificial intelligence.'),
('Emma White', 27, 'https://randomuser.me/api/portraits/women/7.jpg', 'Emma is a veterinarian who has a special connection with animals.'),
('Lucas Brown', 38, 'https://randomuser.me/api/portraits/men/8.jpg', 'Lucas is a retired soldier who now works as a security consultant.'),
('Isabella Martinez', 29, 'https://randomuser.me/api/portraits/women/9.jpg', 'Isabella is a fashion designer with a flair for vintage styles.'),
('Aiden Davis', 33, 'https://randomuser.me/api/portraits/men/10.jpg', 'Aiden is a struggling actor looking for his big break in Hollywood.'),
('Mia Wilson', 26, 'https://randomuser.me/api/portraits/women/11.jpg', 'Mia is a marine biologist dedicated to preserving ocean life.'),
('Elijah Perez', 39, 'https://randomuser.me/api/portraits/men/12.jpg', 'Elijah is a history professor with a passion for ancient civilizations.'),
('Ava Taylor', 31, 'https://randomuser.me/api/portraits/women/13.jpg', 'Ava is a yoga instructor who believes in the power of mindfulness.'),
('James Anderson', 45, 'https://randomuser.me/api/portraits/men/14.jpg', 'James is a successful businessman with a hidden talent for painting.'),
('Charlotte Clark', 28, 'https://randomuser.me/api/portraits/women/15.jpg', 'Charlotte is a cybersecurity expert who fights against cybercrime.'),
('Alexander Baker', 34, 'https://randomuser.me/api/portraits/men/16.jpg', 'Alexander is a pilot who loves the freedom of the open skies.'),
('Amelia Green', 25, 'https://randomuser.me/api/portraits/women/17.jpg', 'Amelia is a social media influencer promoting sustainable living.'),
('Daniel Evans', 36, 'https://randomuser.me/api/portraits/men/18.jpg', 'Daniel is a firefighter who bravely saves lives in his community.'),
('Scarlett Wright', 30, 'https://randomuser.me/api/portraits/women/19.jpg', 'Scarlett is a novelist known for her gripping crime thrillers.'),
('Logan King', 32, 'https://randomuser.me/api/portraits/men/20.jpg', 'Logan is an adventurous travel blogger exploring hidden gems around the world.'),
('Zoe Garcia', 27, 'https://randomuser.me/api/portraits/women/21.jpg', 'Zoe is a fitness trainer who inspires her clients to achieve their goals.'),
('Jackson Martinez', 40, 'https://randomuser.me/api/portraits/men/22.jpg', 'Jackson is a renowned architect with a vision for sustainable design.'),
('Natalie Young', 29, 'https://randomuser.me/api/portraits/women/23.jpg', 'Natalie is a zoologist who studies rare species in remote jungles.'),
('Henry Hernandez', 37, 'https://randomuser.me/api/portraits/men/24.jpg', 'Henry is a mechanic who restores classic cars in his spare time.'),
('Lily Adams', 26, 'https://randomuser.me/api/portraits/women/25.jpg', 'Lily is a florist with a talent for creating stunning floral arrangements.'),
('Christopher Garcia', 33, 'https://randomuser.me/api/portraits/men/26.jpg', 'Christopher is a musician who writes soulful songs about love and loss.'),
('Victoria Lewis', 31, 'https://randomuser.me/api/portraits/women/27.jpg', 'Victoria is a lawyer fighting for justice in a corrupt legal system.'),
('Wyatt Cooper', 39, 'https://randomuser.me/api/portraits/men/28.jpg', 'Wyatt is a detective who never gives up until he solves the case.'),
('Penelope Reed', 28, 'https://randomuser.me/api/portraits/women/29.jpg', 'Penelope is a chef specializing in fusion cuisine that delights the senses.'),
('Gabriel Ward', 35, 'https://randomuser.me/api/portraits/men/30.jpg', 'Gabriel is an investigative journalist uncovering government secrets.'),
('Sofia Hill', 24, 'https://randomuser.me/api/portraits/women/31.jpg', 'Sofia is a kindergarten teacher who brings joy to her students every day.'),
('Leo Ramirez', 42, 'https://randomuser.me/api/portraits/men/32.jpg', 'Leo is a stuntman who thrives on adrenaline and danger.'),
('Madison Murphy', 30, 'https://randomuser.me/api/portraits/women/33.jpg', 'Madison is an archaeologist digging up ancient mysteries.'),
('Owen Stewart', 31, 'https://randomuser.me/api/portraits/men/34.jpg', 'Owen is a software engineer creating innovative apps to make life easier.'),
('Chloe Scott', 27, 'https://randomuser.me/api/portraits/women/35.jpg', 'Chloe is a psychologist helping people overcome their inner demons.'),
('Ethan Bennett', 38, 'https://randomuser.me/api/portraits/men/36.jpg', 'Ethan is a park ranger who protects wildlife in national parks.'),
('Grace Carter', 29, 'https://randomuser.me/api/portraits/women/37.jpg', 'Grace is a botanist discovering new plant species in remote jungles.'),
('Aaron Ward', 33, 'https://randomuser.me/api/portraits/men/38.jpg', 'Aaron is a chef with a passion for creating mouthwatering desserts.');
